baseURL = 'https://vanvj00002.github.io/monkvan/'
languageCode = 'zh-cn'
title = 'monkvan'
theme = 'ananke'

[params]
description = '老梵的个人随笔和思考'
author = '老梵'
showVisitedLinks = true
showReadingTime = true
summaryLength = 200

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "归档"
url = "/archives/"
weight = 2

[[menu.main]]
name = "关于"
url = "/about/"
weight = 3
